server:
  port: 8080
  locale: uk

elasticsearch:
  host: http://localhost:9200

payment:
  stripe:
    secret: replace_it

logging:
  level:
    org:
      springframework:
        security=DEBUG:
    org.springframework.web.cors: TRACE
    org.springframework.security: TRACE
    org.springframework.cloud.gateway: TRACE

spring:
  application:
    name: app
  data:
    redis:
      host: localhost
      port: 6380
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  ai:
    openai:
      api-key: replace_it
      chat:
        options:
          model: gpt-4o-mini

urls:
  paths:
    authServer: localhost
    frontend: http://localhost:4200
